In [1]:
#!pip install --upgrade fastai 
!pip install -qq aicrowd-cli==0.1

In [2]:
API_KEY = 'PERSONAL API KEY' #Please enter your API Key from [https://www.aicrowd.com/participants/me]
!aicrowd login --api-key $API_KEY

API Key valid
Saved API Key successfully!


In [3]:
!aicrowd dataset download --challenge wineq

sample_submission.csv: 100% 1.97k/1.97k [00:00<00:00, 106kB/s]
test.csv: 100% 50.9k/50.9k [00:00<00:00, 849kB/s]
train.csv: 100% 212k/212k [00:00<00:00, 1.40MB/s]


In [4]:
!rm -rf data
!mkdir data

!mv train.csv data/train.csv
!mv test.csv data/test.csv
!mv sample_submission.csv data/sample_submission.csv

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score

In [6]:
path = "data/train.csv" 

In [7]:
df = pd.read_csv(path)

In [8]:
df.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.0              0.27         0.36  ...       0.45      8.8        6
1            8.4              0.40         0.70  ...       0.64      9.7        5
2            7.8              0.17         0.23  ...       0.41     10.7        7
3            6.2              0.18         0.49  ...       0.37     11.6        6
4            6.5              0.26         0.24  ...       0.40     10.1        6

[5 rows x 12 columns]

In [9]:
X = df.drop("quality", axis=1)
y = df["quality"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.20, 
                                                    random_state=40)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [12]:
model = RandomForestClassifier().fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.6619897959183674

In [13]:
from sklearn.metrics import classification_report,confusion_matrix

In [14]:
print(classification_report(y_test,y_pred))
print('\n')
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         3
           4       0.67      0.12      0.21        32
           5       0.66      0.66      0.66       234
           6       0.64      0.79      0.71       357
           7       0.73      0.49      0.59       132
           8       0.81      0.52      0.63        25
           9       0.00      0.00      0.00         1

    accuracy                           0.66       784
   macro avg       0.50      0.37      0.40       784
weighted avg       0.67      0.66      0.65       784



[[  0   0   1   2   0   0   0]
 [  0   4  19   9   0   0   0]
 [  0   1 154  77   2   0   0]
 [  0   1  57 283  16   0   0]
 [  0   0   1  63  65   3   0]
 [  0   0   0   6   6  13   0]
 [  0   0   0   1   0   0   0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
final_test_path = "data/test.csv"
final_test = pd.read_csv(final_test_path)

In [16]:
submission = model.predict(final_test)

In [17]:
submission = pd.DataFrame(submission) 
submission.to_csv('submission.csv',header=['quality'],index=False)

In [18]:
!aicrowd submission create -c wineq -f submission.csv

submission.csv ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 3.6/2.0 KB • ? • 0:00:00
                                  ╭─────────────────────────╮                                  
                                  │ Successfully submitted! │                                  
                                  ╰─────────────────────────╯                                  
                                        Important links                                        
┌──────────────────┬──────────────────────────────────────────────────────────────────────────┐
│  This submission │ https://www.aicrowd.com/challenges/wineq/submissions/127417              │
│                  │                                                                          │
│  All submissions │ https://www.aicrowd.com/challenges/wineq/submissions?my_submissions=true │
│                  │                                                                          │
│      Leaderboard │ https://www.aicrowd.com/challenges